name: test-and-deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Setup PostgreSQL Database
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'my_db'
          postgresql user: 'test_user'
          postgresql password: 'test_password'

      - name: Install Dependencies
        run: npm ci

      - name: Run Test-suites
        run: PGDATABASE=my_db PGUSER=test_user PGPASSWORD=test_password JWTSECRET=${{secrets.JWT_SECRET}} TEST_CREDENTIALS=${{secrets.JWT_TEST_CREDENTIALS}} npm t

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          HD_JWTSECRET: ${{secrets.JWT_SECRET}}
